In [1]:
#importing libraries
import pandas as pd
import numpy as np
import nltk
import os
from nltk.tokenize import sent_tokenize, word_tokenize
import re
from nltk.corpus import stopwords 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer

 
    
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report


import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud




In [4]:
os.chdir('C:/Users/SivaKumar/Documents/cutetext')

In [6]:
#reading data
text=pd.read_csv('data.csv')

In [7]:
text.head()

Category                                        Description
0         1  meat manager Industrial Production manager Foo...
1         2  territory manager Sales manager Beverage and T...
2         1  senior vice president digital magazine act Chi...
3         1  supervisor technical service First-Line Superv...
4         1  registered nurse resource management Registere...

In [5]:
text.head()

Category                                        Description
0         1  meat manager Industrial Production manager Foo...
1         2  territory manager Sales manager Beverage and T...
2         1  senior vice president digital magazine act Chi...
3         1  supervisor technical service First-Line Superv...
4         1  registered nurse resource management Registere...

In [4]:
#text['edited'] = text['Description'].str.replace("[^a-zA-Z]", " ")
 

In [6]:
#text['edited'] = text['Description'].str.replace("[\s+]", " ")


In [7]:
#removing punctuals with regular expressions
for i in range(len(text)):
    text['Description'][i]=re.sub(r'[^A-Za-z]', ' ', text['Description'][i]) 

C:\Users\SivaKumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [8]:
text.head()

Category                                        Description
0         1  meat manager Industrial Production manager Foo...
1         2  territory manager Sales manager Beverage and T...
2         1  senior vice president digital magazine act Chi...
3         1  supervisor technical service First Line Superv...
4         1  registered nurse resource management Registere...

In [9]:
#substituting double space with single space
for i in range(len(text)):
    text['Description'][i]=re.sub(r'[\s+]', ' ', text['Description'][i]) 

C:\Users\SivaKumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [10]:
text.head()

Category                                        Description
0         1  meat manager Industrial Production manager Foo...
1         2  territory manager Sales manager Beverage and T...
2         1  senior vice president digital magazine act Chi...
3         1  supervisor technical service First Line Superv...
4         1  registered nurse resource management Registere...

In [11]:
#converting into lower case
text['Description'] = text['Description'].str.lower()

In [12]:
text.head()

Category                                        Description
0         1  meat manager industrial production manager foo...
1         2  territory manager sales manager beverage and t...
2         1  senior vice president digital magazine act chi...
3         1  supervisor technical service first line superv...
4         1  registered nurse resource management registere...

# word tokenization

In [13]:
for i in range(len(text)):
    text['Description'][i]=word_tokenize(text['Description'][i]) 
 

C:\Users\SivaKumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [14]:
text.head()

Category                                        Description
0         1  [meat, manager, industrial, production, manage...
1         2  [territory, manager, sales, manager, beverage,...
2         1  [senior, vice, president, digital, magazine, a...
3         1  [supervisor, technical, service, first, line, ...
4         1  [registered, nurse, resource, management, regi...

# stop words removal

In [15]:
stop_words = set(stopwords.words('english'))
print(stop_words)

{'d', 'our', 'above', "she's", 'where', 'to', 'won', 'been', 'does', 'it', 'their', "you'd", 'in', 'your', 'hadn', 'through', 'yourself', 'had', "needn't", "haven't", 'mightn', 'how', 'll', 'theirs', 'same', 'or', 're', 'at', 'why', 'i', "aren't", 'just', 'were', 'doing', 'y', 'and', "doesn't", 'shouldn', "weren't", 'some', 'aren', "mustn't", "wasn't", 'against', "hadn't", 'ma', 'than', 'so', 'any', 'shan', 'you', 'into', 'no', 'couldn', "don't", 'from', 'am', 'of', 'as', 'he', 'herself', 'very', 'o', "shan't", 'all', 'those', "it's", 'which', 'during', 'will', 'don', 'yourselves', 'because', 'them', 'they', "couldn't", 'for', 'are', 'once', 'while', "you've", 'ourselves', 'being', 'now', 'having', "didn't", 'only', 've', "should've", 'has', 'then', 'themselves', 'be', 'myself', 'ours', "you're", 'an', 'up', "hasn't", 'nor', 'further', 'm', 'both', 'me', 'the', 'few', 'this', 'here', 'most', 'when', 'can', 'if', 'wasn', 'itself', 'such', 'needn', 'its', 'again', 'after', 'until', 'whom

In [16]:
for i in range(len(text)):
    text['Description'][i] = [token for token in text['Description'][i] if token not in stop_words]


C:\Users\SivaKumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [17]:
text.Description[0]

['meat',
 'manager',
 'industrial',
 'production',
 'manager',
 'food',
 'beverage',
 'stores']

In [18]:
print(text[:20])

    Category                                        Description
0          1  [meat, manager, industrial, production, manage...
1          2  [territory, manager, sales, manager, beverage,...
2          1  [senior, vice, president, digital, magazine, a...
3          1  [supervisor, technical, service, first, line, ...
4          1  [registered, nurse, resource, management, regi...
5          1  [registered, nurse, speciality, registered, nu...
6          2  [territory, manager, iii, sales, manager, beve...
7          1  [case, dock, laborer, laborers, freight, stock...
8          1  [machine, operator, ww, packaging, filling, ma...
9          1  [work, cell, operator, production, workers, fu...
10         1  [ct, technician, radiologic, technicians, hosp...
11         1  [producer, producers, administrative, support,...
12         1  [occupational, therapist, occupational, therap...
13         1  [visual, inspector, inspectors, testers, sorte...
14         1  [seasonal, registered, nur

In [19]:
#text['Description']= text['Description'].apply(lambda x: ' '.join([w for w in x.split() if len(w)>3]))   removing the whuch are less than 3 letters

# lematizing

In [20]:
lmtzr = nltk.stem.WordNetLemmatizer()


In [21]:
for i in range(len(text)):
    text['Description'][i] = [lmtzr.lemmatize(plural) for plural in text['Description'][i]]



C:\Users\SivaKumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [22]:
text.Description[0]


['meat',
 'manager',
 'industrial',
 'production',
 'manager',
 'food',
 'beverage',
 'store']

In [23]:
for i in range(len(text)):
    text['Description'][i] =' '.join(text['Description'][i])

    

C:\Users\SivaKumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [24]:
text.head()

Category                                        Description
0         1  meat manager industrial production manager foo...
1         2  territory manager sale manager beverage tobacc...
2         1  senior vice president digital magazine act chi...
3         1  supervisor technical service first line superv...
4         1  registered nurse resource management registere...

# train test split on preprocessed  text data

In [25]:
x_train, x_val, y_train, y_val = train_test_split(text['Description'],text['Category'],test_size = 0.2, random_state = 200)

In [26]:
x_train.head()

2808    director chief executive professional scientif...
49      associate retail salesperson religious grantma...
2901    registered nurse surgery registered nurse admi...
236     territory manager iii sale manager beverage to...
448     mnt technician ii institution elc dietetic tec...
Name: Description, dtype: object

# vectorization

In [27]:
#count vectorization
textf = CountVectorizer(stop_words='english',lowercase=True,strip_accents='unicode',decode_error='ignore')


In [28]:
word_matrix=textf.fit_transform(x_train)

In [29]:
word_matrix

<2386x619 sparse matrix of type '<class 'numpy.int64'>'
	with 19261 stored elements in Compressed Sparse Row format>

In [30]:
dense_matrix=word_matrix.todense()   #to convert sparse matrix into dense form

In [31]:
dense_matrix.shape

(2386, 619)

In [32]:
word_matrixtest=textf.transform(x_val)

In [33]:
word_matrixtest

<597x619 sparse matrix of type '<class 'numpy.int64'>'
	with 4733 stored elements in Compressed Sparse Row format>

In [34]:
dense_matrixtest=word_matrixtest.todense()
dense_matrixtest.shape

(597, 619)

In [35]:
#tfidf vectorization
tfidf_transformer = TfidfVectorizer(ngram_range=(1,1),stop_words='english')
X_train_tfid = tfidf_transformer.fit_transform(x_train)
X_test_tfid = tfidf_transformer.transform(x_val)


In [36]:
#ignores incase of warnings
import warnings
warnings.filterwarnings('ignore')

#  logistic model 

In [37]:
# logistic model with count vectorization
logistic=LogisticRegression()
logmod=logistic.fit(word_matrix,y_train)

In [38]:
trainpred=logmod.predict(word_matrix)

In [39]:
testpred=logmod.predict(word_matrixtest)

In [40]:
from sklearn.metrics import confusion_matrix

In [41]:
confusion_matrix(testpred,y_val)

array([[375,   1,   1],
       [  2, 189,   4],
       [  1,   1,  23]], dtype=int64)

In [42]:
accuracy_score(y_train,trainpred)


0.9895222129086337

In [43]:
accuracy_score(y_val,testpred)


0.983249581239531

In [44]:
print(classification_report(y_train,trainpred))


              precision    recall  f1-score   support

           1       1.00      1.00      1.00      1574
           2       0.98      0.99      0.98       706
           3       0.94      0.87      0.90       106

    accuracy                           0.99      2386
   macro avg       0.97      0.95      0.96      2386
weighted avg       0.99      0.99      0.99      2386



In [45]:
#naive bayes model with count vectorization

mb=MultinomialNB().fit(word_matrix,y_train)

In [46]:
trainpredm=mb.predict(word_matrix)

In [47]:
testpredm=mb.predict(word_matrixtest)

In [48]:
confusion_matrix(trainpredm,y_train)

array([[1460,    4,    0],
       [  52,  690,   11],
       [  62,   12,   95]], dtype=int64)

In [49]:
confusion_matrix(testpredm,y_val)

array([[355,   0,   0],
       [ 12, 188,   3],
       [ 11,   3,  25]], dtype=int64)

In [50]:
accuracy_score(y_train,trainpredm)


0.940905280804694

In [51]:
accuracy_score(y_val,testpredm)
 

0.9514237855946399

In [52]:
print(classification_report(y_train,trainpredm))


              precision    recall  f1-score   support

           1       1.00      0.93      0.96      1574
           2       0.92      0.98      0.95       706
           3       0.56      0.90      0.69       106

    accuracy                           0.94      2386
   macro avg       0.83      0.93      0.87      2386
weighted avg       0.95      0.94      0.94      2386



In [53]:
#logistic model with tfidf
logistic3=LogisticRegression()
logmod3=logistic3.fit(X_train_tfid,y_train)

In [54]:
trainpred3=logmod3.predict(X_train_tfid)

In [55]:
testpred3=logmod3.predict(X_test_tfid)

In [56]:
confusion_matrix(trainpred3,y_train)

array([[1571,   10,    3],
       [   3,  689,   13],
       [   0,    7,   90]], dtype=int64)

In [57]:
confusion_matrix(testpred3,y_val)

array([[377,   1,   3],
       [  0, 189,   4],
       [  1,   1,  21]], dtype=int64)

In [58]:
accuracy_score(y_train,trainpred3)


0.9849119865884325

In [59]:
accuracy_score(y_val,testpred3)


0.983249581239531

In [60]:
print(classification_report(y_train,trainpred3))

              precision    recall  f1-score   support

           1       0.99      1.00      0.99      1574
           2       0.98      0.98      0.98       706
           3       0.93      0.85      0.89       106

    accuracy                           0.98      2386
   macro avg       0.97      0.94      0.95      2386
weighted avg       0.98      0.98      0.98      2386



In [61]:
#multi naive bayes with tfidf
mb4=MultinomialNB().fit(X_train_tfid,y_train)

In [62]:
trainpred4=mb4.predict(X_train_tfid)

In [63]:
testpred4=mb4.predict(X_test_tfid)

In [64]:
confusion_matrix(trainpred4,y_train)

array([[1554,    9,    7],
       [  20,  696,   30],
       [   0,    1,   69]], dtype=int64)

In [65]:
confusion_matrix(testpred4,y_val)

array([[372,   2,   2],
       [  5, 189,   8],
       [  1,   0,  18]], dtype=int64)

In [66]:
accuracy_score(y_train,trainpred4)


0.9719195305951384

In [67]:
accuracy_score(y_val,testpred4)


0.9698492462311558

In [68]:
print(classification_report(y_train,trainpred4))

              precision    recall  f1-score   support

           1       0.99      0.99      0.99      1574
           2       0.93      0.99      0.96       706
           3       0.99      0.65      0.78       106

    accuracy                           0.97      2386
   macro avg       0.97      0.87      0.91      2386
weighted avg       0.97      0.97      0.97      2386



In [ ]:
# Of all  the models logistic model with count vectorized operation performs better


In [ ]:
#  weighted average is the better error metric in this case